### ISSUE TITLE
dockergc will not install - v8.5.1-v8.5.8

### ISSUE THREAD

**Issue by dellipse** [PGBlitz/Apps-Core#15]
On PGBlitz v 8.5.1-8.5.7, dockergc will not install

Go to 'PG Box'
Choose PG Box: Core
Choose Utilize Core Box - PlexGuides's
type 'dockergc' and press Enter
type 'deploy' and press Enter

Observe the following error:

`TASK [Install docker-gc-exclude] ***********************************************
Sunday 24 February 2019  22:11:56 -0500 (0:00:00.040)       0:00:02.725 *******
fatal: [127.0.0.1]: FAILED! => {"changed": false, "msg": "Could not find or access '/opt/coreapps/apps/templates/docker-gc-exclude' on the Ansible Controller.\nIf you are using                                                             a module and expect the file to exist on the remote, see the remote_src option"}
        to retry, use: --limit @/opt/coreapps/apps/dockergc.retry
`

Operating System: Ubuntu 18.04
Plexguide Versions: 8.5.1, 8.5.4, 8.5.7
Plexguide Server Type: Remote Dedi
Plexguide Edition: [Gdrive/Local Storage/GCE]
Plexguide Mount System: Move+PGDrive
Using Traefik: Yes
Domain DNS Provider: CloudFlare
OAuth is enabled

**Comment by MrDoobPG** [comment]
Move to  Community-Apps

**Comment by MrDoobPG** [comment]
file moved to Community ! paths fixxed !
[closed]

https://github.com/PGBlitz/Apps-Community/blob/v8.5/apps/dockergc.yml

**Comment by dellipse** [comment]
It is still showing in the core in v8.5.8 (with broken install) and NOT in the community apps.

**Comment by Admin9705** [comment]
ya i never created this yml (and don't have the direct time to focus on this because i don't use it).  i personally don't have the time to go through it, but you can take it up.  I'm closing this here, but mrdoob moved it (which is where it should have been). you can open the issue there :D
