### ISSUE TITLE
Tautulli Needs TZ Environment Variable

### ISSUE THREAD

**Issue by rbhr** [PGBlitz/Apps-Core#17]
Tautulli container is bugging out as it does not have a TZ variable.
This fixed for me but I'm unsure if there is maybe a system or PG variable we can pass more dynamically than this.

    - name: 'Setting PG ENV'
      set_fact:
        pg_env:
          PUID: '1000'
          PGID: '1000'
          TZ: 'Australia/Adelaide'

**Comment by MrDoobPG** [comment]
But not  all user life in Australia  

So we must find another  solution  for this..

**Comment by rbhr** [comment]
I know, so sad for them :)
The boss has made the fix now so you can close this one.

**Comment by MrDoobPG** [comment]
But we can try it over 

cat /etc/timezone and they added as ENV to the docker

**Comment by robertbaker** [comment]
I did the right fix, reinstall and check
