### ISSUE TITLE
Docker Socket Exposure for Jellyfin

### ISSUE THREAD

**Issue by Artiume** [PGBlitz/Apps-Core#30]
Hey, dev over on the Jellyfin Team. I'm working with someone who is having [access issues](https://github.com/jellyfin/jellyfin/issues/2348) to their remote server and they use PG. While looking through how they set everything up, I noticed a few issues with how everything was set up. What's the reasoning behind exposing the docker socket to Jellyfin? I don't see it on any of the other media services. 

https://github.com/PGBlitz/Apps-Core/blob/fa44d7c59b41e1b420865329539c9d052d57a139/apps/jellyfin.yml#L54

**Comment by vFlagR** [comment]
Hi Artiume,

I'm not the main creator of PG, neither am I the most knowledgable about how and why things were set up. However, I've taken it upon myself to try and correct some of the basic issues with PG. I'll do some testing and see if I can figure out why the docker socket is passed to Jellyfin, in the meantime is it doing any harm by being there? I.e. Is it a security or degradation of services risk? 

Apologies for the delayed response and lack of overall knowledge.

Many Thanks,
vFlagR

**Comment by Artiume** [comment]
Afaik, I think once upon a time, ouroborus required socket exposure on any containers it would automatically update, I don't think this a thing still. But for the container itself, there's no need for it to have the socket

**Comment by vFlagR** [comment]
Have removed the offending line and deployed the change to the Apps-Core repo. A re-install using the PG menu should remove the mounted volume without deleting any user data :)

[0824bb425c84835fd1aadbfb270efa078225cc04](https://github.com/PGBlitz/Apps-Core/commit/0824bb425c84835fd1aadbfb270efa078225cc04)
