### ISSUE TITLE
rutorrent fail install/run

### ISSUE THREAD

**Issue by dan3805** [PGBlitz/Apps-Core#45]
[
![IMAGE 2021-01-09 18:25:13](https://user-images.githubusercontent.com/35934387/104110681-0530ce00-52a8-11eb-8829-b9aeafe506f5.jpg)
](url)

![IMAGE 2021-01-09 18:25:24](https://user-images.githubusercontent.com/35934387/104110685-0bbf4580-52a8-11eb-9981-fa49f401d1cb.jpg)

fresh linux install , tested 2 times.

**Comment by dan3805** [comment]
TASK [purge broken plugins file] ***********************************************
Saturday 09 January 2021  23:24:54 +0000 (0:00:00.134)       0:00:42.240 ******
fatal: [127.0.0.1]: FAILED! => {"changed": true, "cmd": "bash /opt/coreapps/apps/templates/rutorrent/rev/remove.sh", "delta": "0:00:00.003102", "end": "2021-01-09 23:24:54.874373", "msg": "non-zero return code", "rc": 127, "start": "2021-01-09 23:24:54.871271", "stderr": "bash: /opt/coreapps/apps/templates/rutorrent/rev/remove.sh: No such file or directory", "stderr_lines": ["bash: /opt/coreapps/apps/templates/rutorrent/rev/remove.sh: No such file or directory"], "stdout": "", "stdout_lines": []}
        to retry, use: --limit @/opt/coreapps/apps/rutorrent.retry

PLAY RECAP *********************************************************************
127.0.0.1                  : ok=95   changed=32   unreachable=0    failed=1

**Comment by dan3805** [comment]
p.s the rutorrent docker remained off after the installation, I opened it manually

**Comment by dan3805** [comment]
p.s.s Current Processing Disk : **IS NOT** /mnt

**Comment by dan3805** [comment]
the install of rutorrent work fine with branch v8.5

**Comment by doob187** [comment]
https://github.com/PGBlitz/Apps-Core/pull/46
